
apiVersion: v1
kind: List          
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
  spec:
    ports:
    - port: 80
      targetPort: 9411
      name: default                    
    selector:
      deploymentconfig: zipkin
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: zipkin
  spec:
    replicas: 3
    selector:
      deploymentconfig: zipkin
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: zipkin
      spec:
        containers:
        - env:
          - name: STORAGE_TYPE
            value: elasticsearch 
          - name: ES_HOSTS
            value: "http://elasticsearch:9200/"
          image:  openzipkin/zipkin
          name: zipkin
          ports:
          - containerPort: 9411
            name: default                    
            protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: zipkin
  spec:
    to:
      kind: Service
      name: zipkin
