apiVersion: v1
kind: Template
metadata:
  name: Zipkin-Cluster
  annotations:
    description: "Deploys a Zipkin cluster"
    tags: zipkin,tracing

parameters:
- name: NAMESPACE
  description: "OpenShift project (current namespace)"
  required: true
- name: CLUSTER_NAME
  description: "Name of the Zipkin cluster"
  value: zipkin-cluster
- name: IMAGE
  description: "Image to deploy"
  value: openzipkin/zipkin
- name: ES_HOSTS
  description: "Elastisearch Hosts seperated by comma"
  required: true
- name: JAVA_OPTS
  displayName: Java runtime options
  description: Options to customise the Java runtime. E.g. -Xms512m -Xmx512m
  value: "-Xms256m -Xmx2048m"

objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: zipkin
  spec:
    ports:
    - port: 80
      targetPort: 9411
      name: default                    
    selector:
      deploymentconfig: zipkin
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: zipkin
  spec:
    replicas: 3
    selector:
      deploymentconfig: zipkin
    strategy:
      # We set the type of strategy to Recreate, which means that it will be scaled down prior to being scaled up
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: zipkin
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: ${JAVA_OPTS}
          - name: STORAGE_TYPE
            value: elasticsearch 
          - name: ES_HOSTS
            value: ${ES_HOSTS}
          image:  ${IMAGE}
          name: zipkin
          ports:
          - containerPort: 9411
            name: default                    
            protocol: TCP
- apiVersion: v1
  kind: Route
  metadata:
    name: zipkin
  spec:
    to:
      kind: Service
      name: zipkin
